version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: sankar007
      MINIO_ROOT_PASSWORD: sankar007
    command: server --console-address ":9001" /data
