version: '3'

services:
  nestjs-social-media-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8002:8002'
      - '8001:8001'
    environment:
      MINIO_ENDPOINT: host.docker.internal
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: 1t8XEa2lBPFBJCyotJus
      MINIO_SECRETKEY: xvKMSWqteqp4NRi47Pd8cFw3R4R4cU2ddzYAHFoR
      MINIO_BUCKET: social-media
      MONGO_INITDB_ROOT_USERNAME: sankar007
      MONGO_INITDB_ROOT_PASSWORD: sankar007
      DB_HOST: host.docker.internal
      MONGO_PORT: 27017
    volumes:
      - ./src:/app/src
    depends_on:
      - minio
    networks:
      - socialmedia

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: sankar007
      MONGO_INITDB_ROOT_PASSWORD: sankar007
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: sankar007
      MINIO_ROOT_PASSWORD: sankar007
    command: server --console-address ":9001" /data
    networks:
      - socialmedia
networks:
  socialmedia:
