apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nestjs-social-media-server
  name: nestjs-social-media-server
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8002
    - name: "8001"
      port: 8001
      targetPort: 8001
  externalIPs:
    - '172.25.248.11'
  selector:
    io.kompose.service: nestjs-social-media-server
status:
  loadBalancer: {}
